_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null

params:
  model.name: resnet18, densenet121
  dataset.name: mnist,cifar10
  num_clients: ${shared_sweeper_params.num_clients}
  num_rounds: 50
  exp_key: ${shared_sweeper_params.exp_key}
  clients_per_round: ${shared_sweeper_params.clients_per_round}
  dirichlet_alpha: 0.1,0.2,0.3,0.4,0.5
